// Created by iWeb 3.0.4 local-build-20151002

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_0:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,441),url:'6_Lecture_%40_IAAC,_Barcelona,_by_Yael_Reisner_%26_Mauel_Jimenez_Garcia,_11th_November_2014_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'6_Lecture_%40_IAAC,_Barcelona,_by_Yael_Reisner_%26_Mauel_Jimenez_Garcia,_11th_November_2014_files/stroke_1.png'},{rect:new IWRect(1,-1,590,2),url:'6_Lecture_%40_IAAC,_Barcelona,_by_Yael_Reisner_%26_Mauel_Jimenez_Garcia,_11th_November_2014_files/stroke_2.png'},{rect:new IWRect(591,-1,2,2),url:'6_Lecture_%40_IAAC,_Barcelona,_by_Yael_Reisner_%26_Mauel_Jimenez_Garcia,_11th_November_2014_files/stroke_3.png'},{rect:new IWRect(591,1,2,441),url:'6_Lecture_%40_IAAC,_Barcelona,_by_Yael_Reisner_%26_Mauel_Jimenez_Garcia,_11th_November_2014_files/stroke_4.png'},{rect:new IWRect(591,442,2,3),url:'6_Lecture_%40_IAAC,_Barcelona,_by_Yael_Reisner_%26_Mauel_Jimenez_Garcia,_11th_November_2014_files/stroke_5.png'},{rect:new IWRect(1,442,590,3),url:'6_Lecture_%40_IAAC,_Barcelona,_by_Yael_Reisner_%26_Mauel_Jimenez_Garcia,_11th_November_2014_files/stroke_6.png'},{rect:new IWRect(-1,442,2,3),url:'6_Lecture_%40_IAAC,_Barcelona,_by_Yael_Reisner_%26_Mauel_Jimenez_Garcia,_11th_November_2014_files/stroke_7.png'}],new IWSize(592,443))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('6_Lecture_@_IAAC,_Barcelona,_by_Yael_Reisner_&_Mauel_Jimenez_Garcia,_11th_November_2014_files/6_Lecture_@_IAAC,_Barcelona,_by_Yael_Reisner_&_Mauel_Jimenez_Garcia,_11th_November_2014Moz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
