// Created by iWeb 3.0.4 local-build-20151002

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_1:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,1020),url:'15_%40_Woodbury_University_-_Woodbury_Gallery_-_The_Drawing_Room,_1st_March_2015_with_Sir_Peter_Cook_%26_Yael_Reisner_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'15_%40_Woodbury_University_-_Woodbury_Gallery_-_The_Drawing_Room,_1st_March_2015_with_Sir_Peter_Cook_%26_Yael_Reisner_files/stroke_1.png'},{rect:new IWRect(1,-1,584,2),url:'15_%40_Woodbury_University_-_Woodbury_Gallery_-_The_Drawing_Room,_1st_March_2015_with_Sir_Peter_Cook_%26_Yael_Reisner_files/stroke_2.png'},{rect:new IWRect(585,-1,3,2),url:'15_%40_Woodbury_University_-_Woodbury_Gallery_-_The_Drawing_Room,_1st_March_2015_with_Sir_Peter_Cook_%26_Yael_Reisner_files/stroke_3.png'},{rect:new IWRect(585,1,3,1020),url:'15_%40_Woodbury_University_-_Woodbury_Gallery_-_The_Drawing_Room,_1st_March_2015_with_Sir_Peter_Cook_%26_Yael_Reisner_files/stroke_4.png'},{rect:new IWRect(585,1021,3,2),url:'15_%40_Woodbury_University_-_Woodbury_Gallery_-_The_Drawing_Room,_1st_March_2015_with_Sir_Peter_Cook_%26_Yael_Reisner_files/stroke_5.png'},{rect:new IWRect(1,1021,584,2),url:'15_%40_Woodbury_University_-_Woodbury_Gallery_-_The_Drawing_Room,_1st_March_2015_with_Sir_Peter_Cook_%26_Yael_Reisner_files/stroke_6.png'},{rect:new IWRect(-1,1021,2,2),url:'15_%40_Woodbury_University_-_Woodbury_Gallery_-_The_Drawing_Room,_1st_March_2015_with_Sir_Peter_Cook_%26_Yael_Reisner_files/stroke_7.png'}],new IWSize(586,1022)),shadow_0:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('15_@_Woodbury_University_-_Woodbury_Gallery_-_The_Drawing_Room,_1st_March_2015_with_Sir_Peter_Cook_&_Yael_Reisner_files/15_@_Woodbury_University_-_Woodbury_Gallery_-_The_Drawing_Room,_1st_March_2015_with_Sir_Peter_Cook_&_Yael_ReisnerMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
