// Created by iWeb 3.0.4 local-build-20151002

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,877),url:'1_Lecture_%40_University_Of_Innsbruck__studio3_Institut_fur_experimentelle_Architektur-_The_Tangible_Utopias_Lecture_Series,_24th_June_2015_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'1_Lecture_%40_University_Of_Innsbruck__studio3_Institut_fur_experimentelle_Architektur-_The_Tangible_Utopias_Lecture_Series,_24th_June_2015_files/stroke_1.png'},{rect:new IWRect(1,-1,587,2),url:'1_Lecture_%40_University_Of_Innsbruck__studio3_Institut_fur_experimentelle_Architektur-_The_Tangible_Utopias_Lecture_Series,_24th_June_2015_files/stroke_2.png'},{rect:new IWRect(588,-1,2,2),url:'1_Lecture_%40_University_Of_Innsbruck__studio3_Institut_fur_experimentelle_Architektur-_The_Tangible_Utopias_Lecture_Series,_24th_June_2015_files/stroke_3.png'},{rect:new IWRect(588,1,2,877),url:'1_Lecture_%40_University_Of_Innsbruck__studio3_Institut_fur_experimentelle_Architektur-_The_Tangible_Utopias_Lecture_Series,_24th_June_2015_files/stroke_4.png'},{rect:new IWRect(588,878,2,3),url:'1_Lecture_%40_University_Of_Innsbruck__studio3_Institut_fur_experimentelle_Architektur-_The_Tangible_Utopias_Lecture_Series,_24th_June_2015_files/stroke_5.png'},{rect:new IWRect(1,878,587,3),url:'1_Lecture_%40_University_Of_Innsbruck__studio3_Institut_fur_experimentelle_Architektur-_The_Tangible_Utopias_Lecture_Series,_24th_June_2015_files/stroke_6.png'},{rect:new IWRect(-1,878,2,3),url:'1_Lecture_%40_University_Of_Innsbruck__studio3_Institut_fur_experimentelle_Architektur-_The_Tangible_Utopias_Lecture_Series,_24th_June_2015_files/stroke_7.png'}],new IWSize(589,879)),shadow_0:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),shadow_2:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),shadow_1:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('1_Lecture_@_University_Of_Innsbruck__studio3_Institut_fur_experimentelle_Architektur-_The_Tangible_Utopias_Lecture_Series,_24th_June_2015_files/1_Lecture_@_University_Of_Innsbruck__studio3_Institut_fur_experimentelle_Architektur-_The_Tangible_Utopias_Lecture_Series,_24th_June_2015Moz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
