// Created by iWeb 3.0.4 local-build-20151002

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_0:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,61),url:'25_April_2014,_Taking_part_at_Lebbeus_Woods_-_Tributes_and_Reminiscences_in_Cooper_Union,_School_of_Architecture,_NYC_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'25_April_2014,_Taking_part_at_Lebbeus_Woods_-_Tributes_and_Reminiscences_in_Cooper_Union,_School_of_Architecture,_NYC_files/stroke_1.png'},{rect:new IWRect(1,-1,570,2),url:'25_April_2014,_Taking_part_at_Lebbeus_Woods_-_Tributes_and_Reminiscences_in_Cooper_Union,_School_of_Architecture,_NYC_files/stroke_2.png'},{rect:new IWRect(571,-1,2,2),url:'25_April_2014,_Taking_part_at_Lebbeus_Woods_-_Tributes_and_Reminiscences_in_Cooper_Union,_School_of_Architecture,_NYC_files/stroke_3.png'},{rect:new IWRect(571,1,2,61),url:'25_April_2014,_Taking_part_at_Lebbeus_Woods_-_Tributes_and_Reminiscences_in_Cooper_Union,_School_of_Architecture,_NYC_files/stroke_4.png'},{rect:new IWRect(571,62,2,3),url:'25_April_2014,_Taking_part_at_Lebbeus_Woods_-_Tributes_and_Reminiscences_in_Cooper_Union,_School_of_Architecture,_NYC_files/stroke_5.png'},{rect:new IWRect(1,62,570,3),url:'25_April_2014,_Taking_part_at_Lebbeus_Woods_-_Tributes_and_Reminiscences_in_Cooper_Union,_School_of_Architecture,_NYC_files/stroke_6.png'},{rect:new IWRect(-1,62,2,3),url:'25_April_2014,_Taking_part_at_Lebbeus_Woods_-_Tributes_and_Reminiscences_in_Cooper_Union,_School_of_Architecture,_NYC_files/stroke_7.png'}],new IWSize(572,63)),shadow_1:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('25_April_2014,_Taking_part_at_Lebbeus_Woods_-_Tributes_and_Reminiscences_in_Cooper_Union,_School_of_Architecture,_NYC_files/25_April_2014,_Taking_part_at_Lebbeus_Woods_-_Tributes_and_Reminiscences_in_Cooper_Union,_School_of_Architecture,_NYCMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
