// Created by iWeb 3.0.4 local-build-20151002

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,351),url:'31_Take_my_Hand_appears_at_the_AD_magazine_by_Wiley,_May_2015_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'31_Take_my_Hand_appears_at_the_AD_magazine_by_Wiley,_May_2015_files/stroke_1.png'},{rect:new IWRect(1,-1,259,2),url:'31_Take_my_Hand_appears_at_the_AD_magazine_by_Wiley,_May_2015_files/stroke_2.png'},{rect:new IWRect(260,-1,3,2),url:'31_Take_my_Hand_appears_at_the_AD_magazine_by_Wiley,_May_2015_files/stroke_3.png'},{rect:new IWRect(260,1,3,351),url:'31_Take_my_Hand_appears_at_the_AD_magazine_by_Wiley,_May_2015_files/stroke_4.png'},{rect:new IWRect(260,352,3,2),url:'31_Take_my_Hand_appears_at_the_AD_magazine_by_Wiley,_May_2015_files/stroke_5.png'},{rect:new IWRect(1,352,259,2),url:'31_Take_my_Hand_appears_at_the_AD_magazine_by_Wiley,_May_2015_files/stroke_6.png'},{rect:new IWRect(-1,352,2,2),url:'31_Take_my_Hand_appears_at_the_AD_magazine_by_Wiley,_May_2015_files/stroke_7.png'}],new IWSize(261,353)),shadow_0:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('31_Take_my_Hand_appears_at_the_AD_magazine_by_Wiley,_May_2015_files/31_Take_my_Hand_appears_at_the_AD_magazine_by_Wiley,_May_2015Moz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
