// Created by iWeb 3.0.4 local-build-20151002

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_2:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,261),url:'25_Rose_Petal_Light_Wall_-_an_outdoors_inflatable_,_March_2015_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'25_Rose_Petal_Light_Wall_-_an_outdoors_inflatable_,_March_2015_files/stroke_1.png'},{rect:new IWRect(1,-1,585,2),url:'25_Rose_Petal_Light_Wall_-_an_outdoors_inflatable_,_March_2015_files/stroke_2.png'},{rect:new IWRect(586,-1,3,2),url:'25_Rose_Petal_Light_Wall_-_an_outdoors_inflatable_,_March_2015_files/stroke_3.png'},{rect:new IWRect(586,1,3,261),url:'25_Rose_Petal_Light_Wall_-_an_outdoors_inflatable_,_March_2015_files/stroke_4.png'},{rect:new IWRect(586,262,3,2),url:'25_Rose_Petal_Light_Wall_-_an_outdoors_inflatable_,_March_2015_files/stroke_5.png'},{rect:new IWRect(1,262,585,2),url:'25_Rose_Petal_Light_Wall_-_an_outdoors_inflatable_,_March_2015_files/stroke_6.png'},{rect:new IWRect(-1,262,2,2),url:'25_Rose_Petal_Light_Wall_-_an_outdoors_inflatable_,_March_2015_files/stroke_7.png'}],new IWSize(587,263)),shadow_0:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),shadow_1:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('25_Rose_Petal_Light_Wall_-_an_outdoors_inflatable_,_March_2015_files/25_Rose_Petal_Light_Wall_-_an_outdoors_inflatable_,_March_2015Moz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');BlogFixupPreviousNext();fixAllIEPNGs('../../../../Media/transparent.gif');applyEffects()}
