// Created by iWeb 3.0.4 local-build-20151002

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,70),url:'9_Take_My_Hand_-_Rights_%26_Weddings_in_Placa_de_la_Merce,_Barcelona_-_Projects_submission_to_the_to_the_FEM,_May_2014_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'9_Take_My_Hand_-_Rights_%26_Weddings_in_Placa_de_la_Merce,_Barcelona_-_Projects_submission_to_the_to_the_FEM,_May_2014_files/stroke_1.png'},{rect:new IWRect(1,-1,70,2),url:'9_Take_My_Hand_-_Rights_%26_Weddings_in_Placa_de_la_Merce,_Barcelona_-_Projects_submission_to_the_to_the_FEM,_May_2014_files/stroke_2.png'},{rect:new IWRect(71,-1,2,2),url:'9_Take_My_Hand_-_Rights_%26_Weddings_in_Placa_de_la_Merce,_Barcelona_-_Projects_submission_to_the_to_the_FEM,_May_2014_files/stroke_3.png'},{rect:new IWRect(71,1,2,70),url:'9_Take_My_Hand_-_Rights_%26_Weddings_in_Placa_de_la_Merce,_Barcelona_-_Projects_submission_to_the_to_the_FEM,_May_2014_files/stroke_4.png'},{rect:new IWRect(71,71,2,2),url:'9_Take_My_Hand_-_Rights_%26_Weddings_in_Placa_de_la_Merce,_Barcelona_-_Projects_submission_to_the_to_the_FEM,_May_2014_files/stroke_5.png'},{rect:new IWRect(1,71,70,2),url:'9_Take_My_Hand_-_Rights_%26_Weddings_in_Placa_de_la_Merce,_Barcelona_-_Projects_submission_to_the_to_the_FEM,_May_2014_files/stroke_6.png'},{rect:new IWRect(-1,71,2,2),url:'9_Take_My_Hand_-_Rights_%26_Weddings_in_Placa_de_la_Merce,_Barcelona_-_Projects_submission_to_the_to_the_FEM,_May_2014_files/stroke_7.png'}],new IWSize(72,72)),shadow_2:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),shadow_1:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),shadow_0:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('9_Take_My_Hand_-_Rights_&_Weddings_in_Placa_de_la_Merce,_Barcelona_-_Projects_submission_to_the_to_the_FEM,_May_2014_files/9_Take_My_Hand_-_Rights_&_Weddings_in_Placa_de_la_Merce,_Barcelona_-_Projects_submission_to_the_to_the_FEM,_May_2014Moz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
