// Created by iWeb 3.0.4 local-build-20151002

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_0:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,760),url:'16_April_2014,_The_nursery_Grup_Roig,_Barcelona,_nurtures_the_Snow_Princess_flowers_%28also_called_Sweet_Alison%29_for_the_Take_My_Hand_installation_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'16_April_2014,_The_nursery_Grup_Roig,_Barcelona,_nurtures_the_Snow_Princess_flowers_%28also_called_Sweet_Alison%29_for_the_Take_My_Hand_installation_files/stroke_1.png'},{rect:new IWRect(1,-1,570,2),url:'16_April_2014,_The_nursery_Grup_Roig,_Barcelona,_nurtures_the_Snow_Princess_flowers_%28also_called_Sweet_Alison%29_for_the_Take_My_Hand_installation_files/stroke_2.png'},{rect:new IWRect(571,-1,2,2),url:'16_April_2014,_The_nursery_Grup_Roig,_Barcelona,_nurtures_the_Snow_Princess_flowers_%28also_called_Sweet_Alison%29_for_the_Take_My_Hand_installation_files/stroke_3.png'},{rect:new IWRect(571,1,2,760),url:'16_April_2014,_The_nursery_Grup_Roig,_Barcelona,_nurtures_the_Snow_Princess_flowers_%28also_called_Sweet_Alison%29_for_the_Take_My_Hand_installation_files/stroke_4.png'},{rect:new IWRect(571,761,2,3),url:'16_April_2014,_The_nursery_Grup_Roig,_Barcelona,_nurtures_the_Snow_Princess_flowers_%28also_called_Sweet_Alison%29_for_the_Take_My_Hand_installation_files/stroke_5.png'},{rect:new IWRect(1,761,570,3),url:'16_April_2014,_The_nursery_Grup_Roig,_Barcelona,_nurtures_the_Snow_Princess_flowers_%28also_called_Sweet_Alison%29_for_the_Take_My_Hand_installation_files/stroke_6.png'},{rect:new IWRect(-1,761,2,3),url:'16_April_2014,_The_nursery_Grup_Roig,_Barcelona,_nurtures_the_Snow_Princess_flowers_%28also_called_Sweet_Alison%29_for_the_Take_My_Hand_installation_files/stroke_7.png'}],new IWSize(572,763))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('16_April_2014,_The_nursery_Grup_Roig,_Barcelona,_nurtures_the_Snow_Princess_flowers_(also_called_Sweet_Alison)_for_the_Take_My_Hand_installation_files/16_April_2014,_The_nursery_Grup_Roig,_Barcelona,_nurtures_the_Snow_Princess_flowers_(also_called_Sweet_Alison)_for_the_Take_My_Hand_installationMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
