// Created by iWeb 3.0.4 local-build-20151002

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,407),url:'20_%40_GSD_Harvard,_on_the_10th_December_2014,_Peter_Cook_Studio,_Jury_with_Perry_Kulper,_Mike_Webb,_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'20_%40_GSD_Harvard,_on_the_10th_December_2014,_Peter_Cook_Studio,_Jury_with_Perry_Kulper,_Mike_Webb,_files/stroke_1.png'},{rect:new IWRect(1,-1,543,2),url:'20_%40_GSD_Harvard,_on_the_10th_December_2014,_Peter_Cook_Studio,_Jury_with_Perry_Kulper,_Mike_Webb,_files/stroke_2.png'},{rect:new IWRect(544,-1,3,2),url:'20_%40_GSD_Harvard,_on_the_10th_December_2014,_Peter_Cook_Studio,_Jury_with_Perry_Kulper,_Mike_Webb,_files/stroke_3.png'},{rect:new IWRect(544,1,3,407),url:'20_%40_GSD_Harvard,_on_the_10th_December_2014,_Peter_Cook_Studio,_Jury_with_Perry_Kulper,_Mike_Webb,_files/stroke_4.png'},{rect:new IWRect(544,408,3,2),url:'20_%40_GSD_Harvard,_on_the_10th_December_2014,_Peter_Cook_Studio,_Jury_with_Perry_Kulper,_Mike_Webb,_files/stroke_5.png'},{rect:new IWRect(1,408,543,2),url:'20_%40_GSD_Harvard,_on_the_10th_December_2014,_Peter_Cook_Studio,_Jury_with_Perry_Kulper,_Mike_Webb,_files/stroke_6.png'},{rect:new IWRect(-1,408,2,2),url:'20_%40_GSD_Harvard,_on_the_10th_December_2014,_Peter_Cook_Studio,_Jury_with_Perry_Kulper,_Mike_Webb,_files/stroke_7.png'}],new IWSize(545,409)),shadow_0:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('20_@_GSD_Harvard,_on_the_10th_December_2014,_Peter_Cook_Studio,_Jury_with_Perry_Kulper,_Mike_Webb,_files/20_@_GSD_Harvard,_on_the_10th_December_2014,_Peter_Cook_Studio,_Jury_with_Perry_Kulper,_Mike_Webb,Moz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
